[project]
name = "aigun-rickandmorty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faster-whisper>=1.2.1",
    "numpy>=2.5.1",
    "openwakeword>=0.6.0",
    "sounddevice>=0.5.5",
    "webrtcvad-wheels>=2.0.14",
]

[tool.uv]
environments = ["sys_platform == 'win32'"]